name: Build and Release Windows Archive

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Archive build output
        run: |
          mkdir dist
          copy build\Release\QRConnect.exe dist\QRConnect.exe
        shell: cmd

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          body: |
            Automated build from main branch.
          files: dist/QRConnect.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
